### ISSUE TITLE
Warning In Console

### ISSUE THREAD

**Issue by vertigojones** [hyber1z0r/react-router-hash-link-offset#1]
First of all, love the plug-in and it's been a huge help for me.

Just wanted to let you know that I'm getting a warning in the console - "React does not recognize the `scrollOffset` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `scrolloffset` instead. If you accidentally passed it from a parent component, remove it from the DOM element."

Not a deal-breaker, just sounds like another case of an older syntax being depreciated. The code still works fine as intended so I'm not too worried about it.

Cheers,

Owen.

**Comment by heyitsjhu** [comment]
Getting this as well. Would be nice if this can be fixed. 
![image](https://user-images.githubusercontent.com/14210200/51219839-95b9bb00-18e7-11e9-9822-72990783febc.png)

**Comment by heyitsjhu** [comment]
@hyber1z0r - I opened a PR #2 that uses de-structuring to separate the offsetScroll prop from the rest of the props before passing the props through to the Link component. This should resolve the console log warning issue.

**Comment by hyber1z0r** [comment]
Thanks for noticing this, as i didn't notice it my self. I've approved @heyitsjhu's PR #2 and will release a new version to npm once it's merged. Have a great weekend.
